### PR TITLE
added dark theme. inspired by dark photo room mood

### PR DESCRIPTION
**Pull request by miroque**
also I was impressed by [f.lux](https://justgetflux.com) 's mode "night mode" and wanted reprodues something similar

and now i'm using it mostly all time, hoping, somebody also liked it

### CODE REVIEW

**Comment by musm** [comment]
pic ?

cc @joonro

**Comment by miroque** [comment]
I added image to my commit, but how to renew pull request.. or reate new one..

**Comment by miroque** [comment]
created commit with image

**Comment by joonro** [comment]
Sorry, I think I merged the PR before you committed it - please make another feature branch from `develop` (not from `master`) and create another PR. Thank you!

**Pull request merged**
