### PR TITLE
Update README with instructions on how to add all the themes available delete 

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
cc @joonro

**Comment by musm** [comment]
cc @joonro

**Comment by joonro** [comment]
Hi - sorry for the late reply. Could you please change the base branch to `develop` instead of `master` so I can merge the PR? I tried to do it but it did not work for some reason - thanks a lot!

**Comment by joonro** [comment]
Hi - sorry for the late reply. Could you please change the base branch to `develop` instead of `master` so I can merge the PR? I tried to do it but it did not work for some reason - thanks a lot!

**Comment by joonro** [comment]
Hi - sorry for the late reply. Could you please change the base branch to `develop` instead of `master` so I can merge the PR? I tried to do it but it did not work for some reason - thanks a lot!

**Comment by musm** [comment]
Thank you ¡

**Pull request merged**
