### PR TITLE
add theme Tango Dark

### PR DESCRIPTION
**Pull request by rkitover**
Data used from:

http://iterm2colorschemes.com/

### CODE REVIEW

**Comment by rkitover** [comment]
Hi, is my theme ok? It seems to work fine for me.

**Comment by joonro** [comment]
Hi - I'm very sorry for the late reply! I must have missed this. And thank you very much for the PR.

**Comment by joonro** [comment]
Oops .. just realized that I shouldn't have merged this to master. :) Anyway, thanks!

**Comment by rkitover** [comment]
Thank you for merging! This is my favorite terminal theme, I think it is/was the default in ubuntu.

**Pull request merged**
