### PR TITLE
add: gruvbox light theme

### PR DESCRIPTION
**Pull request by Linerre**
Hi Joonro,

This pull request would like to add `gruvbox-light` theme to your collection of themes. I'm a great fan of gruvbox theme and these days I especially prefer the light one, which is missing in the current set. A screenshot can be found attached:

gruvbox-light

### CODE REVIEW

**Comment by Linerre** [comment]
Sorry I forgot to move the file to the `themes' directory. I don't know if it is appropriate to create another pull request for such minor change. Could you please move it to the right place if you decide to merge the PR? Many thanks.

**Comment by joonro** [comment]
Merged. Thank you very much for the PR. I will make appropriate changes before I merge it into master.

**Comment by joonro** [comment]
By the way, the original color for `ColorTable15` made numbers illegible, so I used the Dark Magenta color for it (it seems purple was used for numbers in the original color scheme).

**Comment by Linerre** [comment]
> 
> 
> By the way, the original color for `ColorTable15` made numbers illegible, so I used the Dark Magenta color for it (it seems purple was used for numbers in the original color scheme).

Thank you for revising and merging. I think you are right. Purple (or magenta) was used for numbers and some statement keywords in the original scheme. I didn't realize `ColorTable15` would do sth undesired to numbers. Anyway, good to know it's been fixed. Really appreciate it.

**Comment by joonro** [comment]
Of course! My pleasure.

**Pull request merged**
